/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_systems"];
        put?: never;
        post: operations["post_systems"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{systemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_system"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_systems_systemId"];
        trace?: never;
    };
    "/systems/{systemId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_systems_draft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{systemId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_systems_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/systems/{systemId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_systems_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system-versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_system_versions_versionId"];
        trace?: never;
    };
    "/system-versions/{versionId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_system_versions_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_systems: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        systems: {
                            /** Format: uuid */
                            systemId: string;
                            name: string;
                            access: string;
                            lifecycle: "active" | "archived";
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                        nextCursor: string | null;
                        requestId: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    post_systems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    source: {
                        /** @constant */
                        kind: "blank";
                        name: string;
                    } | {
                        /** @constant */
                        kind: "clone";
                        /** Format: uuid */
                        versionId: string;
                    } | {
                        /** @constant */
                        kind: "import";
                        content: string;
                    };
                    idempotencyKey: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workspace: {
                            system: {
                                /** Format: uuid */
                                systemId: string;
                                name: string;
                                access: string;
                                lifecycle: "active" | "archived";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            draft: {
                                revision: number;
                                document: {
                                    [key: string]: unknown;
                                };
                                sourceChecksum: string;
                                /** Format: uuid */
                                updatedBy: string;
                                /** Format: date-time */
                                updatedAt: string;
                            } | null;
                            versions: {
                                /** Format: uuid */
                                versionId: string;
                                /** Format: uuid */
                                systemId: string;
                                semanticVersion: string;
                                checksum: string;
                                releaseNotes: string;
                                lifecycle: string;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            assessment: {
                                ok: boolean;
                                diagnostics: {
                                    code: string;
                                    path: string;
                                    message: string;
                                }[];
                            };
                        };
                        requestId: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    get_system: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                systemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workspace: {
                            system: {
                                /** Format: uuid */
                                systemId: string;
                                name: string;
                                access: string;
                                lifecycle: "active" | "archived";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            draft: {
                                revision: number;
                                document: {
                                    [key: string]: unknown;
                                };
                                sourceChecksum: string;
                                /** Format: uuid */
                                updatedBy: string;
                                /** Format: date-time */
                                updatedAt: string;
                            } | null;
                            versions: {
                                /** Format: uuid */
                                versionId: string;
                                /** Format: uuid */
                                systemId: string;
                                semanticVersion: string;
                                checksum: string;
                                releaseNotes: string;
                                lifecycle: string;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            assessment: {
                                ok: boolean;
                                diagnostics: {
                                    code: string;
                                    path: string;
                                    message: string;
                                }[];
                            };
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    patch_systems_systemId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                systemId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    lifecycle: "active" | "archived";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lifecycle: {
                            kind: "system" | "version";
                            /** Format: uuid */
                            systemId: string;
                            /** Format: uuid */
                            versionId?: string;
                            lifecycle: string;
                        };
                        requestId: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    put_systems_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                systemId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    expectedRevision: number | null;
                    document: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workspace: {
                            system: {
                                /** Format: uuid */
                                systemId: string;
                                name: string;
                                access: string;
                                lifecycle: "active" | "archived";
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            };
                            draft: {
                                revision: number;
                                document: {
                                    [key: string]: unknown;
                                };
                                sourceChecksum: string;
                                /** Format: uuid */
                                updatedBy: string;
                                /** Format: date-time */
                                updatedAt: string;
                            } | null;
                            versions: {
                                /** Format: uuid */
                                versionId: string;
                                /** Format: uuid */
                                systemId: string;
                                semanticVersion: string;
                                checksum: string;
                                releaseNotes: string;
                                lifecycle: string;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                            assessment: {
                                ok: boolean;
                                diagnostics: {
                                    code: string;
                                    path: string;
                                    message: string;
                                }[];
                            };
                        };
                        requestId: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    post_systems_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                systemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        snapshot: {
                            /** Format: uuid */
                            snapshotId: string;
                            /** Format: uuid */
                            systemId: string;
                            sourceRevision: number;
                            package: {
                                [key: string]: unknown;
                            };
                            /** Format: date-time */
                            expiresAt: string;
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    post_systems_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                systemId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    expectedRevision: number;
                    semanticVersion: string;
                    releaseNotes: string;
                    idempotencyKey: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version: {
                            /** Format: uuid */
                            versionId: string;
                            /** Format: uuid */
                            systemId: string;
                            semanticVersion: string;
                            checksum: string;
                            package: {
                                [key: string]: unknown;
                            };
                            releaseNotes: string;
                            lifecycle: string;
                            /** Format: date-time */
                            createdAt: string;
                        };
                        requestId: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    patch_system_versions_versionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @constant */
                    lifecycle: "deprecated";
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        lifecycle: {
                            kind: "system" | "version";
                            /** Format: uuid */
                            systemId: string;
                            /** Format: uuid */
                            versionId?: string;
                            lifecycle: string;
                        };
                        requestId: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
    get_system_versions_export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schemaVersion: string;
                        mediaType: string;
                        exportedAt: string;
                        package: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            /** @constant */
                            code: "unauthorized";
                            message: string;
                        };
                        requestId: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: {
                            code: string;
                            message: string;
                            latestRevision?: number | null;
                            diagnostics?: {
                                code: string;
                                path: string;
                                message: string;
                            }[];
                        };
                        requestId: string;
                    };
                };
            };
        };
    };
}
