export {
  createSystemPersistenceRepository,
  REFERENCE_TEMPLATES,
  seedReferenceTemplates,
  type AuditRecord,
  type DraftRecord,
  type DraftSaveResult,
  type IdempotencyReceipt,
  type PreviewSnapshotRecord,
  type PublishVersionInput,
  type PublishVersionResult,
  type RecordReceiptInput,
  type RecordReceiptResult,
  type ReferenceTemplate,
  type SaveDraftInput,
  type SeedReferenceTemplatesResult,
  type SystemId,
  type SystemPersistenceRepository,
  type SystemRecord,
  type UserId,
  type VersionId,
  type VersionRecord,
} from "./repository.js";