export {
  createSystemPersistenceRepository,
  type AuditRecord,
  type DraftRecord,
  type DraftSaveResult,
  type IdempotencyReceipt,
  type PreviewSnapshotRecord,
  type PublishVersionInput,
  type PublishVersionResult,
  type RecordReceiptInput,
  type RecordReceiptResult,
  type SaveDraftInput,
  type SystemId,
  type SystemPersistenceRepository,
  type SystemRecord,
  type UserId,
  type VersionId,
  type VersionRecord,
} from "./repository.js";